/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ornate-gold-vintage-frame/source/frame.glb --output src/components/portal/FrameModel.tsx --types
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {}
}

export default function FrameModel(props: ThreeElements['group']) {
  const { nodes } = useGLTF('/models/ornate-gold-vintage-frame/source/frame.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/models/ornate-gold-vintage-frame/source/frame.glb')